blank_issues_enabled: false
contact_links:
  - name: FAQs and Known Issues
    url: https://github.com/tqdm/tqdm/#faq-and-known-issues
    about: Frequently asked questions and known issues
  - name: "StackOverflow#tqdm"
    url: https://stackoverflow.com/questions/tagged/tqdm
    about: How-To questions
