[tool.poetry]
name = "mimesis"
version = "4.1.2"
description = "Mimesis: fake data generator."
authors = ["Isaak Uchakaev <likid.geimfari@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
codecov = "^2.1"
flake8 = "^3.8"
flake8-builtins = "^1.5"
flake8-commas = "^2.0"
flake8-quotes = "^3.2"
pytest = "^6.2"
pytest-isort = "^1.1.0"
pytest-cov = "^2.10"
pytest-flake8 = "^1.0"
pytest-mock = "^3.4"
requests = "^2.25"
mypy = "^0.750.0"
colorama = "^0.4.4"
flake8-docstrings = "^1.5"
pyroma = "^2.6"
pygments = "^2.7"
flake8-type-annotations = "^0.1.0"
pytest-randomly = "^3.5"
check-manifest = "^0.45"
readme-renderer = "^28.0"
pytz = "^2020.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
