minor_changes:
  - The AnsiballZ Python wrapper now changes the working directory to ``~`` or ``/`` if the current one is not accessible.
    This allows become to drop privileges on macOS when using pipelining.
