-   id: isort
    name: isort
    entry: isort
    require_serial: true
    language: python
    language_version: python3
    types_or: [cython, pyi, python]
    args: ['--filter-files']
    minimum_pre_commit_version: '2.9.0'
