name: Post Release
on:
  release:
    types: [published]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - name: Checkout docs
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.github.io
        path: docs
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install
      run: |
        pip install -U wheel
        pip install -U -r ./docs/requirements.txt
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        git config --global user.name "$GIT_AUTHOR_NAME"
      env:
        GIT_AUTHOR_NAME: ${{ github.event.sender.login }}
        GIT_AUTHOR_EMAIL: ${{ github.event.sender.login }}@users.noreply.github.com
    - name: Update Wiki Releases
      run: |
        pushd wiki
        make
        git commit -a -m "update release notes to ${GITHUB_REF#refs/tags/}"
        git push
        popd
    - run: make -C docs build
    - if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
      uses: casperdcl/push-dir@v1
      with:
        message: update static site
        branch: gh-pages
        dir: docs/build/docs/_site
        nojekyll: true
        name: tqdm[bot]
        email: 68520887+tqdm-bot@users.noreply.github.com
